### ISSUE TITLE
Menu / download button not working

### ISSUE THREAD

**Issue by Chaphasilor** [Puzzaks/MCPlayer#1]
Using beta 0.0.14, tapping the menu button (3 dots) on the player screen, or the download button on a release overview screen has no effect.  
Is that a known issue?

Device: Asus Zenfone 10, Android (ZenUI) 14

I could try digging deeper for debugging if needed, I have a Flutter environment set up...

**Comment by Puzzak** [comment]
Unfortunately, that part of the app is not yet implemented. It is not a bug, rather a template for what will there be. Also you can try long-pressing in buttons that do nothing, there will be comment if this is not done yet

**Comment by Puzzak** [comment]
Oh hey, this was implemented in the latest release, sorry for not notifying!
